---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    canfar-net-sessionID: "${skaha.sessionid}"
    canfar-net-sessionName: "${skaha.sessionname}"
    canfar-net-sessionType: "${skaha.sessiontype}"
    canfar-net-userid: "${skaha.userid}"
  name: "${skaha.jobname}"
spec:
  {{ template "skaha.job.nodeSelector" . }}
  activeDeadlineSeconds: ${skaha.sessionexpiry}
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      labels:
        canfar-net-sessionID: "${skaha.sessionid}"
        canfar-net-sessionName: "${skaha.sessionname}"
        canfar-net-sessionType: "${skaha.sessiontype}"
        canfar-net-userid: "${skaha.userid}"
        job-name: "${skaha.jobname}"
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      restartPolicy: OnFailure
      ${skaha.schedulegpu}
      imagePullSecrets:
      - name: ${software.imagesecret}
      securityContext:
        runAsUser: ${skaha.posixid}
        runAsGroup: ${skaha.posixid}
        fsGroup: ${skaha.posixid}
        supplementalGroups: [${skaha.supgroups}]
        runAsNonRoot: true
      priorityClassName: uber-user-preempt-medium
      hostname: "${software.hostname}"
      initContainers:
      {{ template "skaha.job.initContainers" . }}
      containers:
      - name: "${skaha.jobname}"
        command: ["/skaha-system/start-desktop.sh"]
        args:
        - ${skaha.hostname}
        env:
        {{ template "skaha.job.environment.desktop" . }}
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        image: ${software.imageid}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
            ephemeral-storage: "2Gi"
          limits:
            memory: "4Gi"
            cpu: "1"
            ephemeral-storage: "10Gi"
        ports:
        - containerPort: 5901
          protocol: TCP
          name: vnc-port
        - containerPort: 6901
          protocol: TCP
          name: novnc-port
        volumeMounts:
        - mountPath: "/etc/passwd"
          name: etc-passwd
          subPath: passwd
        - mountPath: "/etc/group"
          name: etc-group
          subPath: group
        - mountPath: "/desktopstartup"
          name: templates
        - mountPath: "/skaha-system"
          name: start-desktop
        - mountPath: "${SKAHA_TLD}"
          name: cavern-volume
          subPath: "cavern"
        - mountPath: "/scratch"
          name: scratch-dir
          subPath: "${skaha.sessionid}"
      volumes:
      - name: templates
        configMap:
          name: templates
          defaultMode: 0777
      - name: start-desktop
        configMap:
          name: launch-scripts
          defaultMode: 0777
      - name: cavern-volume
        persistentVolumeClaim:
          claimName: skaha-workload-cavern-pvc
      - name: scratch-dir
        emptyDir: {}
      - name: init-users-groups
        configMap:
          name: init-users-groups-config
          defaultMode: 0777
      - name: etc-group
        emptyDir: {}
      - name: etc-passwd
        emptyDir: {}
