{{- range .Values.platformInstances }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .apiNamespace }}

---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .sessionsNamespace }}
{{- end }}
