{{- range .Values.platformInstances }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: {{ .sessionsNamespace }}-role
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["pods", "jobs", "middlewares", "services"]
  verbs: ["get", "watch", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: {{ .sessionsNamespace }}-role-binding
subjects:
- kind: ServiceAccount
  namespace: {{ .apiNamespace }}
  name: skaha # Name is case sensitive
roleRef:
  kind: ClusterRole
  name: {{ .sessionsNamespace }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
