name: "CI: Testing"

on:
    pull_request:
      branches: [main]
    push:
      branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Run Tests
        run: |
            cd skaha
            ./gradlew clean check
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: skaha-unittests-coverage
          path: skaha/build/reports/jacoco/test/jacocoTestReport.xml
          if-no-files-found: error
          retention-days: 1
          overwrite: true

  codecov:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - name: Download coverage artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: skaha-unittests-coverage
      - name: List Downloaded Artifacts
        run: |
            echo "Downloaded artifacts:"
            ls -lah $GITHUB_WORKSPACE
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: jacocoTestReport.xml
          flags: skaha-unittests-coverage
          name: skaha-unittests-coverage
          fail_ci_if_error: true
          verbose: true
